CA="https://acme-v02.api.letsencrypt.org/directory"
CHALLENGETYPE="http-01"
WELLKNOWN="/home/telemazer/phoenix-gateway/var/acme"
BASEDIR="/var/lib/dehydrated"
DOMAINS_TXT="/etc/dehydrated/eirinchan-domains.txt"
HOOK="/usr/local/libexec/eirinchan-cert-hook"
HOOK_CHAIN="yes"
KEY_ALGO="secp384r1"
RENEW_DAYS="30"
