defmodule Eirinchan.WhaleStickers.Defaults do
  @moduledoc false

  # Each sticker is defined once. The containing list owns its formatting-page
  # column and the tuple order owns its position within that column.
  @formatting_columns [
    left: [
      {"gem", "gem.png", false},
      {"concern2", "concern2.png", false},
      {"milk", "milk.png", false},
      {"ninacry", "ninacry.png", false},
      {"smell", "smell.png", false},
      {"tempura", "tempura.png", false},
      {"tenfact", "tenfact.png", false},
      {"grimace", "grimace.png", false},
      {"wow", "wow.gif", false},
      {"ahegao", "ahegao.png", false},
      {"nvke", "nvke.gif", false},
      {"headphones", "headphones.png", false},
      {"cinema", "cinema.png", false},
      {"masaka2", "masaka2.jpg", false},
      {"krillin", "krillin.png", false},
      {"rika", "rika.jpg", false},
      {"ominous", "ominous.png", false},
      {"kanmarisa", "kanmarisa.png", false},
      {"mask", "mask.png", false},
      {"banjo", "banjo.png", false},
      {"pout", "pout.png", false},
      {"notes", "notes.png", false},
      {"elated", "elated.png", false},
      {"dogshit", "dogshit.gif", false},
      {"mid2", "mid2.gif", false},
      {"gojo", "gojo.png", false},
      {"angry2", "angry2.png", false},
      {"17", "17funny.png", false},
      {"yeah", "yeah.png", false},
      {"vibe", "vibe.gif", false},
      {"thumb", "thumb.png", false},
      {"waka", "waka.png", false},
      {"damn", "damn.png", false},
      {"yikes", "yikes.png", false},
      {"cackle", "cackle.png", false},
      {"whale", "whale1.png", true},
      {"glasses", "glassesoff.png", false},
      {"fact", "whalefact.png", false},
      {"fact2", "fact2.png", false},
      {"thinking", "thinking.png", false},
      {"bruh", "whalebruh.png", false},
      {"unyu", "unyu.png", false},
      {"angry", "angry.png", false},
      {"lmao", "lmao2.png", false},
      {"dora", "dora.png", false},
      {"boom", "boom.png", false},
      {"gasp", "gasp.png", false},
      {"kys", "kys.png", false},
      {"bald", "bald.gif", false},
      {"meow", "meow.png", false},
      {"rofl", "rofl.png", false},
      {"pensive", "pensive.png", false}
    ],
    right: [
      {"fact3", "fact3.png", false},
      {"pensive2", "pensive2.png", false},
      {"horse", "horse.png", false},
      {"kasawalk", "tsukasa.gif", false},
      {"cum", "cum.gif", false},
      {"imhungry", "hungry.png", false},
      {"mindbreak2", "mindbreak2.gif", false},
      {"scaremu", "scaremu.png", false},
      {"number", "number.gif", false},
      {"wemywhale", "wemywhale.png", false},
      {"cinema2", "cinemasanae.png", false},
      {"bbccry", "bbccry.gif", false},
      {"gn", "gn.gif", false},
      {"ramen2", "ramen2.png", false},
      {"gokek", "gokek.jpg", false},
      {"ramen", "ramen.png", false},
      {"wink", "wink.png", false},
      {"mindbreak", "mindbreak.png", false},
      {"masaka", "masaka.png", false},
      {"sip", "sip.png", false},
      {"seppuku", "seppuku.png", false},
      {"bruh2", "bruh3.png", false},
      {"lebron", "lebron.gif", false},
      {"peak", "peak.gif", false},
      {"peak2", "peak2.gif", false},
      {"mid", "mid.gif", false},
      {"dance", "dance.gif", false},
      {"drool", "drool.png", false},
      {"no", "no.png", false},
      {"brain2", "brain2.png", false},
      {"poop", "poop.png", false},
      {"theory", "theory.png", false},
      {"lambda", "lambda.png", false},
      {"shock", "shock.png", false},
      {"shock2", "shock2.png", false},
      {"upvote", "upvote.png", false},
      {"youmu", "youmu.png", false},
      {"pipe", "pipe.png", false},
      {"happy", "happy.png", false},
      {"pog", "keikipog.png", false},
      {"baby", "baby.png", false},
      {"kek", "kek.png", false},
      {"crawl", "crawl.png", false},
      {"neutral", "neutralbaby.png", false},
      {"pray", "prayer.png", false},
      {"frown", "frown.png", false},
      {"cath", "cath.png", false},
      {"concern", "concern.png", false},
      {"gay", "gay.png", false},
      {"sign", "sign.png", false},
      {"fear", "fear.png", false},
      {"brain", "brain.png", false},
      {"feelio", "feelio.png", false},
      {"funny", "17funny.png", false},
      {"syamu", "syamu.jpg", false}
    ]
  ]

  @entries (for {_column, stickers} <- @formatting_columns,
                {token, file, append_break} <- stickers do
              %{token: token, file: file, title: token, append_break: append_break}
            end)

  @formatting_column_tokens Map.new(@formatting_columns, fn {column, stickers} ->
                              {column, Enum.map(stickers, &elem(&1, 0))}
                            end)

  def entries, do: @entries
  def formatting_columns, do: @formatting_column_tokens
end
